import { type InsertLead } from '../shared/schema';

// Sample lead data with negative reasons for testing the Olumsuz Analizi tab
export const sampleLeads: InsertLead[] = [
  {
    // First negative lead - Price issue
    customerId: "C1001",
    contactId: "CT1001",
    customerName: "Ahmet Yılmaz",
    firstCustomerSource: "Google",
    formCustomerSource: "Website",
    webFormNote: "Konutla ilgileniyor. Fiyatı çok yüksek buldu.",
    requestDate: "2025-06-01",
    infoFormLocation1: "Proje A",
    infoFormLocation2: "Konut",
    assignedPersonnel: "Mehmet Özkan",
    reminderPersonnel: "Mehmet Özkan",
    wasCalledBack: "Evet",
    customerResponseDate: "2025-06-02",
    callNote: "Müşteri fiyatı yüksek buldu, düşünecek.",
    oneOnOneMeeting: "Hayır",
    responseResult: "Olumsuz",
    negativeReason: "Fiyat",
    wasSaleMade: "Hayır",
    lastMeetingNote: "Müşteri fiyatın çok yüksek olduğunu söyledi",
    lastMeetingResult: "Olumsuz",
    leadType: "satis",
    status: "Olumsuz"
  },
  {
    // Second negative lead - Location issue
    customerId: "C1002",
    contactId: "CT1002",
    customerName: "Ayşe Demir",
    firstCustomerSource: "Facebook",
    formCustomerSource: "Facebook",
    webFormNote: "2+1 konut arıyor. Konum isteklerine uygun değil.",
    requestDate: "2025-06-03",
    infoFormLocation1: "Proje B",
    infoFormLocation2: "Konut",
    assignedPersonnel: "Fatma Yılmaz",
    wasCalledBack: "Evet",
    customerResponseDate: "2025-06-04",
    callNote: "Müşteri lokasyonu beğenmedi, çok uzak.",
    oneOnOneMeeting: "Hayır",
    responseResult: "Olumsuz",
    negativeReason: "Konum",
    wasSaleMade: "Hayır",
    lastMeetingNote: "Müşteri lokasyonu isteklerine uygun bulmadı",
    lastMeetingResult: "Olumsuz",
    leadType: "satis",
    status: "Olumsuz"
  },
  {
    // Third negative lead - Budget issue
    customerId: "C1003",
    contactId: "CT1003",
    customerName: "Mehmet Kaya",
    firstCustomerSource: "Instagram",
    formCustomerSource: "Instagram",
    webFormNote: "3+1 konut arıyor. Bütçesi yetersiz.",
    requestDate: "2025-06-05",
    infoFormLocation1: "Proje C",
    infoFormLocation2: "Konut",
    assignedPersonnel: "Alperen Yerlikaya",
    wasCalledBack: "Evet",
    customerResponseDate: "2025-06-06",
    callNote: "Müşterinin bütçesi yetersiz.",
    oneOnOneMeeting: "Evet",
    meetingDate: "2025-06-07",
    responseResult: "Olumsuz",
    negativeReason: "Bütçe",
    wasSaleMade: "Hayır",
    lastMeetingNote: "Müşterinin bütçesi istediği konut için yetersiz",
    lastMeetingResult: "Olumsuz",
    leadType: "satis",
    status: "Olumsuz"
  },
  {
    // Fourth negative lead - Customer changed mind
    customerId: "C1004",
    contactId: "CT1004",
    customerName: "Zeynep Şahin",
    firstCustomerSource: "Referans",
    formCustomerSource: "Referans",
    webFormNote: "2+1 konut arıyor. Müşteri vazgeçti.",
    requestDate: "2025-06-08",
    infoFormLocation1: "Proje D",
    infoFormLocation2: "Konut",
    assignedPersonnel: "Mehmet Özkan",
    wasCalledBack: "Evet",
    customerResponseDate: "2025-06-09",
    callNote: "Müşteri şimdilik almaktan vazgeçti.",
    oneOnOneMeeting: "Hayır",
    responseResult: "Olumsuz",
    negativeReason: "Müşteri Vazgeçti",
    wasSaleMade: "Hayır",
    lastMeetingNote: "Müşteri şimdilik almaktan vazgeçti, ilerleyen zamanlarda tekrar düşünecek",
    lastMeetingResult: "Olumsuz",
    leadType: "satis",
    status: "Olumsuz"
  },
  {
    // Fifth negative lead - Project not liked
    customerId: "C1005",
    contactId: "CT1005",
    customerName: "Emre Aydın",
    firstCustomerSource: "Website",
    formCustomerSource: "Website",
    webFormNote: "1+1 konut arıyor. Projeyi beğenmedi.",
    requestDate: "2025-06-10",
    infoFormLocation1: "Proje E",
    infoFormLocation2: "Konut",
    assignedPersonnel: "Ayşe Demir",
    wasCalledBack: "Evet",
    customerResponseDate: "2025-06-11",
    callNote: "Müşteri projeyi beğenmedi.",
    oneOnOneMeeting: "Evet",
    meetingDate: "2025-06-12",
    responseResult: "Olumsuz",
    negativeReason: "Proje Beğenilmedi",
    wasSaleMade: "Hayır",
    lastMeetingNote: "Müşteri projeyi inceledi fakat beğenmedi",
    lastMeetingResult: "Olumsuz",
    leadType: "satis",
    status: "Olumsuz"
  },
  {
    // Sixth negative lead - Buyer profile not suitable
    customerId: "C1006",
    contactId: "CT1006",
    customerName: "Can Özkan",
    firstCustomerSource: "Instagram",
    formCustomerSource: "Instagram",
    webFormNote: "Villa arıyor. Profili uygun değil.",
    requestDate: "2025-06-13",
    infoFormLocation1: "Proje F",
    infoFormLocation2: "Villa",
    assignedPersonnel: "Murat Şen",
    wasCalledBack: "Evet",
    customerResponseDate: "2025-06-14",
    callNote: "Müşteri profili uygun değil.",
    oneOnOneMeeting: "Hayır",
    responseResult: "Olumsuz",
    negativeReason: "Alıcı Profili Uygun Değil",
    wasSaleMade: "Hayır",
    lastMeetingNote: "Müşterinin kredi profili uygun değil",
    lastMeetingResult: "Olumsuz",
    leadType: "satis",
    status: "Olumsuz"
  },
  {
    // Seventh lead - Positive case for comparison
    customerId: "C1007",
    contactId: "CT1007",
    customerName: "Ebru Çelik",
    firstCustomerSource: "Referans",
    formCustomerSource: "Referans",
    webFormNote: "2+1 konut arıyor. Takipte.",
    requestDate: "2025-06-15",
    infoFormLocation1: "Proje A",
    infoFormLocation2: "Konut",
    assignedPersonnel: "Zeynep Aktaş",
    wasCalledBack: "Evet",
    customerResponseDate: "2025-06-16",
    callNote: "Müşteri düşünecek, takipte.",
    oneOnOneMeeting: "Hayır",
    responseResult: "Takipte",
    wasSaleMade: "Hayır",
    lastMeetingNote: "Müşteri projeyi inceliyor, karar verecek",
    lastMeetingResult: "Takipte",
    leadType: "satis",
    status: "Takipte"
  },
  {
    // Eighth lead - Another positive case
    customerId: "C1008",
    contactId: "CT1008",
    customerName: "Mustafa Yıldız",
    firstCustomerSource: "Google",
    formCustomerSource: "Website",
    webFormNote: "3+1 konut arıyor. İlgileniyor.",
    requestDate: "2025-06-17",
    infoFormLocation1: "Proje B",
    infoFormLocation2: "Konut",
    assignedPersonnel: "Ali Vural",
    wasCalledBack: "Evet",
    customerResponseDate: "2025-06-18",
    callNote: "Müşteri ilgileniyor, toplantı planlandı.",
    oneOnOneMeeting: "Evet",
    meetingDate: "2025-06-20",
    responseResult: "Takipte",
    wasSaleMade: "Hayır",
    lastMeetingNote: "Müşteri olumlu, detaylar görüşülecek",
    lastMeetingResult: "Bilgi Verildi",
    leadType: "satis",
    status: "Bilgi Verildi"
  }
];
